### ISSUE TITLE
运行EXE文件出现bug

### ISSUE THREAD

**Issue by HuangPengCheng666** [Wang-Jingrun/PapersNoteTool#1]
<img width="846" alt="1666510224561" src="https://user-images.githubusercontent.com/115711342/197379908-ee1fe7d1-15ec-4d53-b361-79a3e31a120b.png">
出现了这样的问题，请问哥我应该怎么来处理问题

**Comment by Wang-Jingrun** [comment]
我也是头一次遇到这样的问题，大概查了一下，可以参考这个https://blog.csdn.net/qq_39046854/article/details/115759059
涉及到download_pdf这个函数
