### ISSUE TITLE
我也是头一次遇到这样的问题，大概查了一下，可以参考这个https://blog.csdn.net/qq_39046854/article/details/115759059

### ISSUE THREAD

**Issue by HuangPengCheng666** [Wang-Jingrun/PapersNoteTool#2]
我也是头一次遇到这样的问题，大概查了一下，可以参考这个https://blog.csdn.net/qq_39046854/article/details/115759059
涉及到download_pdf这个函数

_Originally posted by @Wang-Jingrun in https://github.com/Wang-Jingrun/PapersNoteTool/issues/1#issuecomment-1288493861_

**Comment by HuangPengCheng666** [comment]
谢谢哥，是代理相关的原因，希望哥能进一步改进出能批量链接下载的软件，非常感谢哥的帮助，哥B站的视频我也三连了，也推荐给了身边的同学，加油加油！

**Comment by Wang-Jingrun** [comment]
> 谢谢哥，是代理相关的原因，希望哥能进一步改进出能批量链接下载的软件，非常感谢哥的帮助，哥B站的视频我也三连了，也推荐给了身边的同学，加油加油！

感谢支持！
